package aplicacao;

import dao.DAOFactory;
import dao.TarefaDAO;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import modelo.Tarefa;
import javax.swing.JSpinner;

/**
 *
 * @author tysonos
 */
public class EditorTarefa extends javax.swing.JDialog {

    TarefaDAO tarefaDao = DAOFactory.criarTarefaDAO();
    Tarefa tarefa;
    PainelAssuntoGenerico painelAssunto = null;
    int idAssunto;

    public EditorTarefa(java.awt.Frame parent, boolean modal, PainelAssuntoGenerico a, Tarefa t) {
        super(parent, modal);
        initComponents();
        painelAssunto = a;
        idAssunto = painelAssunto.getAssunto().getId();
        this.setTitle(painelAssunto.getAssunto().getTitulo());
        spnPrazoConclusao.setModel(new javax.swing.SpinnerDateModel());
        spnPrazoConclusao.setEditor(new JSpinner.DateEditor(spnPrazoConclusao, "dd/MM/yyyy HH:mm"));
        if (t != null) {
            tarefa = t;
            if (t.getPrazoConclusao() != null) {
                spnPrazoConclusao.setEnabled(true);
                spnPrazoConclusao.setValue(t.getPrazoConclusao());
                checkboxPrazo.setSelected(true);
            }
            campoTitulo.setText(t.getTitulo());
            textareaDescricao.setText(t.getDescricao());
        } else {
            btnRemoverTarefa.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelDescricao = new javax.swing.JLabel();
        campoTitulo = new javax.swing.JTextField();
        checkboxPrazo = new javax.swing.JCheckBox();
        spnPrazoConclusao = new javax.swing.JSpinner();
        labelTitulo = new javax.swing.JLabel();
        btnSalvarTarefa = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textareaDescricao = new javax.swing.JTextArea();
        btnRemoverTarefa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        labelDescricao.setText("Descrição:");

        campoTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTituloActionPerformed(evt);
            }
        });

        checkboxPrazo.setText("Prazo para conclusão");
        checkboxPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkboxPrazoActionPerformed(evt);
            }
        });

        spnPrazoConclusao.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(1743013494122L), null, null, java.util.Calendar.DAY_OF_MONTH));
        spnPrazoConclusao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        spnPrazoConclusao.setEditor(new javax.swing.JSpinner.DateEditor(spnPrazoConclusao, "dd/MM/yyyy - HH:mm"));
        spnPrazoConclusao.setEnabled(false);

        labelTitulo.setText("Titulo:");

        btnSalvarTarefa.setText("Salvar");
        btnSalvarTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarTarefaActionPerformed(evt);
            }
        });

        textareaDescricao.setColumns(20);
        textareaDescricao.setRows(5);
        jScrollPane2.setViewportView(textareaDescricao);

        btnRemoverTarefa.setText("Remover");
        btnRemoverTarefa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverTarefaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelDescricao)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(checkboxPrazo)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoverTarefa)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnSalvarTarefa))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spnPrazoConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(campoTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTitulo))
                .addGap(2, 2, 2)
                .addComponent(labelDescricao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnPrazoConclusao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnSalvarTarefa)
                    .addComponent(btnRemoverTarefa)
                    .addComponent(checkboxPrazo))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void checkboxPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkboxPrazoActionPerformed
        // TODO add your handling code here:
        spnPrazoConclusao.setEnabled(checkboxPrazo.isSelected());
        if (tarefa != null) {
            if (!checkboxPrazo.isSelected()) {
                tarefa.setPrazoConclusao(null);
            }
        }
    }//GEN-LAST:event_checkboxPrazoActionPerformed

    private void campoTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoTituloActionPerformed

    private void btnSalvarTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarTarefaActionPerformed
        // TODO add your handling code here:
        if (campoTitulo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "O campo título não deve estar vazio.");
            campoTitulo.requestFocus();
            return;
        }
        Tarefa novaTarefa = (tarefa == null ? new Tarefa() : null);
        if (novaTarefa == null) {
            editarTarefa();
        } else {
            novaTarefa.setAssunto(painelAssunto.getAssunto().getId());
            novaTarefa.setTitulo(campoTitulo.getText().trim());
            novaTarefa.setDescricao(textareaDescricao.getText().trim());
            novaTarefa.setDataCriacao(Date.from(Instant.now()));
            spnPrazoConclusao.getValue();
            novaTarefa.setConcluida(false);
            if (checkboxPrazo.isSelected()) {
                novaTarefa.setPrazoConclusao((Date) spnPrazoConclusao.getValue());
            }
            try {
                int novoId = tarefaDao.inserir(idAssunto, novaTarefa);
                if (novoId <= 0) {
                    throw new Exception("Erro ao adicionar novo assunto!");
                };
                novaTarefa.setId(novoId);
                painelAssunto.addTarefa(novaTarefa);
                JOptionPane.showMessageDialog(this, "Nova tarefa adicionada com sucesso!");
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnSalvarTarefaActionPerformed

    private void btnRemoverTarefaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverTarefaActionPerformed
        // TODO add your handling code here:
        int res = JOptionPane.showConfirmDialog(this, "Remover tarefa: "
                + tarefa.getTitulo(), null, JOptionPane.YES_NO_OPTION);
        if (res == 0) {
            try {
                tarefaDao.apagar(tarefa.getId());
                painelAssunto.deleteTarefa(tarefa);
                this.dispose();
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage(), "Erro ao remover tarefa", JOptionPane.ERROR_MESSAGE);
            }

        }
    }//GEN-LAST:event_btnRemoverTarefaActionPerformed
    private void editarTarefa() {
        boolean tituloEditado = false;
        boolean descricaoEditado = false;
        boolean prazoEditado = false;
        descricaoEditado = !(textareaDescricao.getText().trim().equals(tarefa.getDescricao()));
        tituloEditado = !(campoTitulo.getText().trim().equals(tarefa.getTitulo()));
        prazoEditado = !(spnPrazoConclusao.getValue().equals(tarefa.getPrazoConclusao()));

        if (descricaoEditado) {
            tarefa.setDescricao(textareaDescricao.getText().trim());
        }
        if (tituloEditado) {
            tarefa.setTitulo(campoTitulo.getText().trim());
        }
        if (prazoEditado) {
            if (checkboxPrazo.isSelected()) {
                tarefa.setPrazoConclusao((Date) spnPrazoConclusao.getValue());
            }
        }
        if (tituloEditado || descricaoEditado || prazoEditado) {
            try {
                tarefaDao.editar(tarefa);
                painelAssunto.updateTarefa(tarefa);
                JOptionPane.showMessageDialog(this, "Edição salva com sucesso!", null, JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, e.getMessage());
            }
        }
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorTarefa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditorTarefa dialog = new EditorTarefa(new javax.swing.JFrame(), true, null, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemoverTarefa;
    private javax.swing.JButton btnSalvarTarefa;
    private javax.swing.JTextField campoTitulo;
    private javax.swing.JCheckBox checkboxPrazo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelDescricao;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JSpinner spnPrazoConclusao;
    private javax.swing.JTextArea textareaDescricao;
    // End of variables declaration//GEN-END:variables
}
